services:

  # np_app:
  #   container_name: np_app
  #   build:
  #     context: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./app:/app/app
  #     - ./tasks:/app/tasks
  #   env_file:
  #     - .env

  np_postgres:
    container_name: np_postgres
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - np_postgres_vol:/data/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Tr7869z9}
    env_file:
      - .env

volumes:
  np_postgres_vol:
  
